// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOyq71GV9b1WmH6vpUM5GemdKqJib5vdI',
    appId: '1:148707701911:web:38ba8cdd7483d0a38b25d2',
    messagingSenderId: '148707701911',
    projectId: 'chatapp-a27a9',
    authDomain: 'chatapp-a27a9.firebaseapp.com',
    storageBucket: 'chatapp-a27a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrrfVanTpkTCA_e3I68bZIo9sT-RvWac',
    appId: '1:148707701911:android:cbb1de3e12ed503a8b25d2',
    messagingSenderId: '148707701911',
    projectId: 'chatapp-a27a9',
    storageBucket: 'chatapp-a27a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4JYBkm2kzDmZyaGIBLgIf40Ys1NNHDw',
    appId: '1:148707701911:ios:860da1f643166ae78b25d2',
    messagingSenderId: '148707701911',
    projectId: 'chatapp-a27a9',
    storageBucket: 'chatapp-a27a9.appspot.com',
    androidClientId: '148707701911-034n56rj4lc4ig5gvi99lfo51056oso5.apps.googleusercontent.com',
    iosClientId: '148707701911-d0gjt1m0ipqb5biho4lkql7pivb8usp2.apps.googleusercontent.com',
    iosBundleId: 'com.timelessfusionapps.smartTalk',
  );
}
